import ToeplitzSOS.ThmA.Defs
import Mathlib

/-!
# the residual-form decomposition — polynomial and sum-of-squares layer

This file proves the bridge from the catalogue polynomial to the generic signed-index
formulation, develops the additive cone of squares of homogeneous quadratics, proves that
the explicit part of the residual-form decomposition belongs to that cone, and relates the two copies of `Hpoly`
to signed-index `Hform`s.
-/

open Finset

noncomputable section

namespace ToeplitzSOS.ThmA

/-! ## Bridge to the catalogue polynomial -/

private lemma X_eq_tmat (n : ℕ) : ToeplitzSOS.X n = tmat n (sv n .x) := by
  funext i j
  have hi := i.isLt
  have hj := j.isLt
  simp only [ToeplitzSOS.X, tmat, sv, ToeplitzSOS.x, ToeplitzSOS.diagIndex]
  rw [dite_eq_left_of_eq_true (eq_true (by omega))]
  congr 2
  ext
  simp
  omega

private lemma Y_eq_tmat (n : ℕ) : ToeplitzSOS.Y n = tmat n (sv n .y) := by
  funext i j
  have hi := i.isLt
  have hj := j.isLt
  simp only [ToeplitzSOS.Y, tmat, sv, ToeplitzSOS.y, ToeplitzSOS.diagIndex]
  rw [dite_eq_left_of_eq_true (eq_true (by omega))]
  congr 2
  ext
  simp
  omega

/-- The catalogue Böttcher--Wenzel polynomial is the generic signed-index form:
`toeplitzBW n = bw n (sv n .x) (sv n .y)`. Used by `toeplitzBW_thmA`,
`Symmetric.toeplitzBW_sym_eq_bw`, `Symmetric.toeplitzBW_skew_eq_bw`, `restrictedBW_eq_bw`. -/
theorem toeplitzBW_eq_bw (n : ℕ) :
    ToeplitzSOS.toeplitzBW n = bw n (sv n .x) (sv n .y) := by
  rw [ToeplitzSOS.toeplitzBW, bw, X_eq_tmat, Y_eq_tmat]

/-! ## The additive SOS cone -/

/-- The additive cone generated by squares of homogeneous quadratic polynomials. -/
def sosCone (σ : Type*) : AddSubmonoid (MvPolynomial σ ℝ) :=
  AddSubmonoid.closure {p | ∃ q : MvPolynomial σ ℝ, q.IsHomogeneous 2 ∧ p = q ^ 2}

/-- Membership in `sosCone` is `IsSumSqHomQuad`. -/
theorem mem_sosCone_iff {σ : Type*} {p : MvPolynomial σ ℝ} :
    p ∈ sosCone σ ↔ ToeplitzSOS.IsSumSqHomQuad p := by
  constructor
  · intro hp
    induction hp using AddSubmonoid.closure_induction with
    | mem p hp =>
        obtain ⟨q, hq, rfl⟩ := hp
        exact ⟨1, fun _ => q, fun _ => hq, by simp⟩
    | zero =>
        exact ⟨0, Fin.elim0, fun j => j.elim0, by simp⟩
    | add p q _ _ hp hq =>
        obtain ⟨N, u, hu, rfl⟩ := hp
        obtain ⟨M, v, hv, rfl⟩ := hq
        refine ⟨N + M, Fin.append u v, ?_, ?_⟩
        · intro j
          refine Fin.addCases (motive := fun j => (Fin.append u v j).IsHomogeneous 2)
            (fun i => ?_) (fun i => ?_) j
          · simpa only [Fin.append_left] using hu i
          · simpa only [Fin.append_right] using hv i
        · simp only [Fin.sum_univ_add, Fin.append_left, Fin.append_right]
  · rintro ⟨N, q, hq, rfl⟩
    apply (sosCone σ).sum_mem
    intro j _
    apply AddSubmonoid.subset_closure
    exact ⟨q j, hq j, rfl⟩

/-- `0 ∈ sosCone`. -/
theorem sosCone_zero {σ : Type*} : (0 : MvPolynomial σ ℝ) ∈ sosCone σ := by
  exact (sosCone σ).zero_mem

/-- `sosCone` is closed under addition. -/
theorem sosCone_add {σ : Type*} {p q : MvPolynomial σ ℝ}
    (hp : p ∈ sosCone σ) (hq : q ∈ sosCone σ) : p + q ∈ sosCone σ := by
  exact (sosCone σ).add_mem hp hq

/-- `sosCone` is closed under finite sums. -/
theorem sosCone_sum {σ ι : Type*} {s : Finset ι} {p : ι → MvPolynomial σ ℝ}
    (hp : ∀ i ∈ s, p i ∈ sosCone σ) : ∑ i ∈ s, p i ∈ sosCone σ := by
  exact (sosCone σ).sum_mem hp

/-- `sosCone` is closed under natural multiples. -/
theorem sosCone_nsmul {σ : Type*} (k : ℕ) {p : MvPolynomial σ ℝ}
    (hp : p ∈ sosCone σ) : k • p ∈ sosCone σ := by
  exact (sosCone σ).nsmul_mem hp k

/-- The square of a quadratic form lies in `sosCone`. -/
theorem sq_mem_sosCone {σ : Type*} {q : MvPolynomial σ ℝ}
    (hq : q.IsHomogeneous 2) : q ^ 2 ∈ sosCone σ := by
  apply AddSubmonoid.subset_closure
  exact ⟨q, hq, rfl⟩

/-! ## Homogeneity of the building blocks -/

/-- The signed-index variables `sv n c a` are linear forms (a variable or `0`). -/
theorem sv_isHomogeneous (n : ℕ) (c : ToeplitzSOS.CoordFamily) (a : ℤ) :
    (sv n c a).IsHomogeneous 1 := by
  unfold sv
  split_ifs
  · exact MvPolynomial.isHomogeneous_X _ _
  · exact MvPolynomial.isHomogeneous_zero _ _ 1

/-- Wedges of the signed-index variables are quadratic forms. -/
theorem wedge_isHomogeneous (n : ℕ) (a b : ℤ) :
    (wedge (sv n .x) (sv n .y) a b).IsHomogeneous 2 := by
  unfold wedge
  exact ((sv_isHomogeneous n .x a).mul (sv_isHomogeneous n .y b)).sub
    ((sv_isHomogeneous n .x b).mul (sv_isHomogeneous n .y a))

/-! ## The explicit summand is SOS -/

private theorem nonneg_intCast_mul_mem_sosCone {σ : Type*} (c : ℤ) (hc : 0 ≤ c)
    {p : MvPolynomial σ ℝ} (hp : p ∈ sosCone σ) :
    (c : MvPolynomial σ ℝ) * p ∈ sosCone σ := by
  have heq : (c : MvPolynomial σ ℝ) * p = c.toNat • p := by
    rw [nsmul_eq_mul]
    congr 1
    rw [← Int.cast_natCast, Int.toNat_of_nonneg hc]
  rw [heq]
  exact sosCone_nsmul c.toNat hp

private theorem Splus_isHomogeneous (n : ℕ) (δ k : ℤ) :
    (Splus n (sv n .x) (sv n .y) δ k).IsHomogeneous 2 := by
  unfold Splus
  apply MvPolynomial.IsHomogeneous.sum
  intro p _
  exact wedge_isHomogeneous n p (p + δ)

private theorem Sminus_isHomogeneous (n : ℕ) (δ k : ℤ) :
    (Sminus n (sv n .x) (sv n .y) δ k).IsHomogeneous 2 := by
  unfold Sminus
  apply MvPolynomial.IsHomogeneous.sum
  intro p _
  exact wedge_isHomogeneous n (-(p + δ)) (-p)

/-- The explicit part of the residual-form decomposition (central squares, Laplacian, slack, same-side coupling
squares; all weights nonnegative integers) is a sum of squares of quadratic forms.
Used by `isSumSqHomQuad_of_Hpoly`. -/
theorem explicitPart_isSumSqHomQuad (n : ℕ) :
    ToeplitzSOS.IsSumSqHomQuad (explicitPart n (sv n .x) (sv n .y)) := by
  rw [← mem_sosCone_iff]
  have hcentral : central n (sv n .x) (sv n .y) ∈ sosCone (ToeplitzSOS.V n) := by
    unfold central
    apply sosCone_sum
    intro P hP
    apply nonneg_intCast_mul_mem_sosCone
    · simp only [mem_Icc] at hP
      have hn : (0 : ℤ) ≤ n := by omega
      have hdiff : (0 : ℤ) ≤ n - P := by omega
      positivity
    · apply sosCone_add
      · exact sq_mem_sosCone (wedge_isHomogeneous n 0 P)
      · exact sq_mem_sosCone (wedge_isHomogeneous n 0 (-P))
  have hlap : lap n (sv n .x) (sv n .y) ∈ sosCone (ToeplitzSOS.V n) := by
    unfold lap
    apply sosCone_sum
    intro σ hσ
    apply sosCone_sum
    intro A hA
    apply sosCone_sum
    intro A' hA'
    apply nonneg_intCast_mul_mem_sosCone
    · simp only [blk, mem_Icc] at hA hA'
      unfold gcoef tau
      omega
    · apply sq_mem_sosCone
      exact (wedge_isHomogeneous n (-A) (σ - A)).sub
        (wedge_isHomogeneous n (-A') (σ - A'))
  have hslack : slack n (sv n .x) (sv n .y) ∈ sosCone (ToeplitzSOS.V n) := by
    unfold slack
    apply sosCone_sum
    intro A hA
    apply sosCone_sum
    intro B hB
    apply nonneg_intCast_mul_mem_sosCone
    · simp only [mem_Icc] at hA hB
      have hn : (0 : ℤ) ≤ n := by omega
      have hdiff : (0 : ℤ) ≤ n - A - B := by omega
      positivity
    · exact sq_mem_sosCone (wedge_isHomogeneous n (-A) B)
  have hcross : cross n (sv n .x) (sv n .y) ∈ sosCone (ToeplitzSOS.V n) := by
    unfold cross
    have hsum :
        (∑ δ ∈ Icc (1 : ℤ) ((n : ℤ) - 2), ∑ k ∈ Ico (0 : ℤ) ((n : ℤ) - 1),
          (Splus n (sv n .x) (sv n .y) δ k +
            Sminus n (sv n .x) (sv n .y) δ k) ^ 2) ∈ sosCone (ToeplitzSOS.V n) := by
      apply sosCone_sum
      intro δ hδ
      apply sosCone_sum
      intro k hk
      apply sq_mem_sosCone
      exact (Splus_isHomogeneous n δ k).add (Sminus_isHomogeneous n δ k)
    rw [two_mul]
    exact sosCone_add hsum hsum
  unfold explicitPart
  exact sosCone_add (sosCone_add (sosCone_add hcentral hlap) hslack) hcross

/-! ## Functoriality and locality of `Hform` -/

/-- `Hform` commutes with ring homomorphisms. -/
theorem Hform_map {R S : Type*} [CommRing R] [CommRing S] (φ : R →+* S)
    (m : ℕ) (x y : ℤ → R) :
    φ (Hform m x y) = Hform m (fun i => φ (x i)) (fun i => φ (y i)) := by
  simp [Hform, wedge, map_sum]

/-- `H_m` depends only on the data at indices `1..m`. -/
theorem Hform_congr {R : Type*} [CommRing R] (m : ℕ)
    {x y x' y' : ℤ → R}
    (hx : ∀ i ∈ Icc (1 : ℤ) m, x i = x' i)
    (hy : ∀ i ∈ Icc (1 : ℤ) m, y i = y' i) :
    Hform m x y = Hform m x' y' := by
  unfold Hform
  congr 1
  · apply sum_congr rfl
    intro i hi
    apply sum_congr rfl
    intro j hj
    have hj' : j ∈ Icc (1 : ℤ) m := by
      simp only [mem_Icc] at hi ⊢
      simp only [mem_Ioc] at hj
      omega
    rw [show wedge x y i j = wedge x' y' i j by
      simp only [wedge, hx i hi, hy i hi, hx j hj', hy j hj']]
  · apply sum_congr rfl
    intro δ hδ
    apply sum_congr rfl
    intro k hk
    congr 1
    apply sum_congr rfl
    intro p hp
    have hp' : p ∈ Icc (1 : ℤ) m := by
      simp only [mem_Icc] at hδ hp ⊢
      simp only [mem_Ico] at hk
      omega
    have hpd : p + δ ∈ Icc (1 : ℤ) m := by
      simp only [mem_Icc] at hδ hp ⊢
      simp only [mem_Ico] at hk
      omega
    simp only [wedge, hx p hp', hy p hp', hx (p + δ) hpd, hy (p + δ) hpd]

/-! ## The positive and negative embeddings of `Hpoly` -/

private theorem rename_hv_plus (n : ℕ) (c : ToeplitzSOS.CoordFamily) (i : ℤ)
    (hi : i ∈ Icc (1 : ℤ) ((n : ℤ) - 1)) :
    MvPolynomial.rename (ιplus n) (hv (n - 1) c i) = sv n c i := by
  simp only [mem_Icc] at hi
  have hn : 1 ≤ n := by
    omega
  have hcast : ((n - 1 : ℕ) : ℤ) = (n : ℤ) - 1 := by omega
  simp only [hv, sv]
  rw [dite_eq_left_of_eq_true (eq_true (by simpa [hcast] using hi))]
  rw [dite_eq_left_of_eq_true (eq_true (by omega))]
  rw [MvPolynomial.rename_X]
  apply congrArg MvPolynomial.X
  apply Prod.ext
  · rfl
  · apply Fin.ext
    simp [ιplus]
    omega

private theorem rename_hv_minus (n : ℕ) (c : ToeplitzSOS.CoordFamily) (i : ℤ)
    (hi : i ∈ Icc (1 : ℤ) ((n : ℤ) - 1)) :
    MvPolynomial.rename (ιminus n) (hv (n - 1) c i) = sv n c (-i) := by
  simp only [mem_Icc] at hi
  have hn : 2 ≤ n := by
    omega
  have hcast : ((n - 1 : ℕ) : ℤ) = (n : ℤ) - 1 := by omega
  simp only [hv, sv]
  rw [dite_eq_left_of_eq_true (eq_true (by simpa [hcast] using hi))]
  rw [dite_eq_left_of_eq_true (eq_true (by omega))]
  rw [MvPolynomial.rename_X]
  apply congrArg MvPolynomial.X
  apply Prod.ext
  · rfl
  · apply Fin.ext
    simp [ιminus]
    omega

/-- `Hpoly (n−1)` renamed by the positive-side embedding is `H_{n−1}` of the signed-index
variables. Used by `toeplitzBW_thmA`. -/
theorem rename_Hpoly_plus (n : ℕ) :
    MvPolynomial.rename (ιplus n) (Hpoly (n - 1)) =
      Hform (n - 1) (sv n .x) (sv n .y) := by
  unfold Hpoly
  change (MvPolynomial.rename (ιplus n)).toRingHom
      (Hform (n - 1) (hv (n - 1) .x) (hv (n - 1) .y)) = _
  rw [Hform_map]
  apply Hform_congr
  · intro i hi
    apply rename_hv_plus
    simp only [mem_Icc] at hi ⊢
    omega
  · intro i hi
    apply rename_hv_plus
    simp only [mem_Icc] at hi ⊢
    omega

/-- `Hpoly (n−1)` renamed by the negative-side embedding is `H_{n−1}` of the reflected
signed-index variables. Used by `toeplitzBW_thmA`. -/
theorem rename_Hpoly_minus (n : ℕ) :
    MvPolynomial.rename (ιminus n) (Hpoly (n - 1)) =
      Hform (n - 1) (fun i => sv n .x (-i)) (fun i => sv n .y (-i)) := by
  unfold Hpoly
  change (MvPolynomial.rename (ιminus n)).toRingHom
      (Hform (n - 1) (hv (n - 1) .x) (hv (n - 1) .y)) = _
  rw [Hform_map]
  apply Hform_congr
  · intro i hi
    apply rename_hv_minus
    simp only [mem_Icc] at hi ⊢
    omega
  · intro i hi
    apply rename_hv_minus
    simp only [mem_Icc] at hi ⊢
    omega

/-! ## Renaming preserves homogeneous quadratic SOS representations -/

end ToeplitzSOS.ThmA

namespace ToeplitzSOS

/-- `IsSumSqHomQuad` is preserved by renaming variables along any map. -/
theorem IsSumSqHomQuad.rename {σ τ : Type*} {p : MvPolynomial σ ℝ}
    (h : IsSumSqHomQuad p) (f : σ → τ) :
    IsSumSqHomQuad (MvPolynomial.rename f p) := by
  obtain ⟨N, q, hq, rfl⟩ := h
  refine ⟨N, fun j => MvPolynomial.rename f (q j), fun j => ?_, ?_⟩
  · exact (hq j).rename_isHomogeneous
  · simp [map_sum]

end ToeplitzSOS

end
